/** Definiciones cortas en español neutro latinoamericano para niños ~9 años. */
export const WORD_DEFINITIONS: Record<string, string> = {
  aburrida: "Que no resulta divertida ni interesante.",
  aburrido: "Que no resulta divertido ni interesante.",
  acariciarlo: "Pasó la mano suavemente sobre él con cariño.",
  acercarse: "Moverse hacia algo o alguien, quedando más cerca.",
  aclaraba: "Hacía que algo se viera más claro o con mejor luz.",
  aclarara: "Se volviera más claro, sin nubes ni niebla.",
  acompañaron: "Fueron con alguien para hacer algo juntos.",
  acompañó: "Fue con alguien para hacer algo juntos.",
  aconsejó: "Le dio un consejo o una buena idea a alguien.",
  acordaron: "Decidieron juntos hacer algo de la misma manera.",
  acuarelas: "Pinturas de colores que se diluyen con agua.",
  adelante: "Hacia el frente, hacia donde uno va.",
  adhesiva: "Que sirve para pegar cosas, como la cinta scotch.",
  admiración: "Sentimiento de respeto y gusto por algo o alguien.",
  adoptaron: "Decidieron hacerlo parte de su familia o grupo.",
  aerostático: "Que funciona con aire caliente para levantarse, como un globo.",
  agradecimiento: "Acto de dar las gracias por algo recibido.",
  agradeció: "Dijo gracias o mostró que valoraba un favor.",
  agujero: "Espacio vacío hecho a propósito o por desgaste.",
  albahaca: "Planta aromática que se usa para dar sabor a la comida.",
  alcanzaban: "Llegaban hasta algo con la mano o moviéndose.",
  alcanzarlo: "Llegar hasta él o conseguirlo.",
  alimentaban: "Le daban comida para que crezca o tenga fuerzas.",
  almohada: "Cojín blando donde apoyamos la cabeza al dormir.",
  aluminio: "Papel plateado y delgado que se usa para envolver comida.",
  amabilidad: "Acto amable y considerado con otra persona.",
  amanecer: "Momento en que sale el sol y empieza el día.",
  amanecía: "Iba saliendo el sol al empezar el día.",
  amanecían: "Salía el sol y comenzaba un nuevo día.",
  amaneció: "Salió el sol y comenzó un nuevo día.",
  amarilla: "De color como el limón o el sol.",
  amarillas: "De color como el limón o el sol.",
  amarillo: "Color como el del sol o de un limón.",
  animales: "Seres vivos que se mueven, como perros, pájaros o ballenas.",
  anotaba: "Escribía algo en un cuaderno para acordarse después.",
  anotaron: "Escribieron algo en un cuaderno para recordarlo.",
  antiguo: "Que es de hace mucho tiempo o que ya tiene muchos años.",
  apagaron: "Hicieron que la luz o el fuego dejara de funcionar.",
  aparatos: "Máquinas o instrumentos que sirven para hacer algo.",
  apareció: "Se hizo visible o llegó de repente.",
  aplaudieron: "Golpearon las manos una contra otra para mostrar alegría.",
  aprendieron: "Descubrieron algo nuevo o adquirieron un saber.",
  apurado: "Con prisa, haciendo las cosas rápido.",
  arreglaban: "Ponían en orden o reparaban algo.",
  arrugado: "Con muchas arrugas o dobleces, no liso.",
  astronomía: "Ciencia que estudia las estrellas, planetas y el espacio.",
  asustarlo: "Hacer que él sienta miedo de repente.",
  asustarse: "Sentir miedo o sobresalto de repente.",
  atardecer: "Momento del día cuando el sol se está poniendo.",
  aterrizar: "Bajar y tocar tierra, como un avión al llegar.",
  aterrizó: "Bajó y tocó tierra al llegar.",
  atraparlo: "Capturarlo para que no se escape.",
  atravesar: "Pasar de un lado al otro de algo.",
  automático: "Que funciona solo, sin que alguien lo haga a cada momento.",
  avanzara: "Se moviera hacia adelante paso a paso.",
  aventura: "Experiencia emocionante con algo de sorpresa o desafío.",
  aventuras: "Experiencias emocionantes y con sorpresas.",
  avergonzaba: "Le daba vergüenza o pena mostrarse.",
  avisara: "Le dijera a alguien algo importante a tiempo.",
  ayudaron: "Colaboraron con alguien para que pudiera lograr algo.",
  bailarina: "Mujer que baila, a menudo de forma profesional.",
  balcón: "Parte de un edificio que sale hacia afuera, con baranda, en un piso alto.",
  biblioteca: "Lugar donde hay muchos libros para leer o pedir prestados.",
  bibliotecaria: "Mujer que trabaja en la biblioteca y ayuda con los libros.",
  bibliotecario: "Hombre que trabaja en la biblioteca y ayuda con los libros.",
  bicicleta: "Vehículo de dos ruedas que se mueve pedaleando.",
  bienvenida: "Saludo amable a alguien que llega o regresa.",
  binoculares: "Instrumento con dos lentes para ver cosas lejanas más grandes.",
  bisabuelo: "Padre del abuelo o de la abuela; familiar muy mayor.",
  cafetería: "Lugar donde se venden comidas y bebidas para tomar allí o llevar.",
  calcetines: "Prendas que cubren los pies dentro del zapato.",
  calendario: "Cuadro o agenda que muestra los días, semanas y meses del año.",
  caminaba: "Iba de un lugar a otro a pie.",
  caminando: "Yendo de un lugar a otro a pie.",
  caminara: "Fuera de un lugar a otro a pie.",
  caminaron: "Fueron de un lugar a otro a pie.",
  caminata: "Recorrido largo hecho caminando.",
  camiseta: "Prenda de algodón que se usa en el torso.",
  campamento: "Lugar al aire libre donde se duerme en carpas y se hacen actividades.",
  campanitas: "Sonidos suaves y claros, como los de una campana pequeña.",
  caracoles: "Animales lentos con concha en espiral.",
  centenario: "Que cumple o cumplió cien años.",
  cerezas: "Frutas pequeñas, redondas y rojas que crecen en pares en un árbol.",
  chocolate: "Dulce suave y sabroso que se hace con cacao; puede ser oscuro o con leche.",
  cobertizo: "Construcción pequeña y sencilla para guardar herramientas o cosas.",
  cocinara: "Preparara comida en la cocina.",
  coincidieron: "Pasó lo mismo o estuvieron en el mismo lugar a la vez.",
  coleccionaba: "Reunía y guardaba objetos del mismo tipo con interés.",
  colocaron: "Pusieron algo en un lugar determinado.",
  compañeros: "Personas que están juntas en clase, trabajo o actividad.",
  compartido: "Usado o disfrutado entre varios, no solo por uno.",
  compartieron: "Dieron o usaron algo entre varios, en conjunto.",
  compostero: "Recipiente o lugar donde se guardan restos para convertirlos en abono.",
  comunidad: "Grupo de personas que viven juntas en un barrio o pueblo.",
  comunitario: "De todos los vecinos o del grupo en conjunto.",
  concentrado: "Muy enfocado en una sola cosa, sin distraerse.",
  conocida: "Que alguien ya sabía o había visto antes.",
  constelación: "Grupo de estrellas en el cielo que forma una figura reconocible.",
  construyeron: "Armaron o fabricaron algo juntando piezas.",
  contadora: "Mujer que lleva las cuentas y los números de una empresa.",
  contenedor: "Recipiente grande donde se tiran o guardan cosas, como la basura.",
  contratiempo: "Problema pequeño que retrasa o complica un plan.",
  controlado: "Hecho con cuidado y sin perder el equilibrio.",
  convertido: "Transformado y pasado a ser otra cosa.",
  convertirse: "Transformarse y pasar a ser otra cosa.",
  coordinadora: "Mujer que organiza y dirige una actividad o grupo.",
  corazones: "Órganos del cuerpo que bombean sangre; también símbolo del amor.",
  cosechado: "Recogido de la tierra cuando ya está listo para comer.",
  crecimiento: "Aumento de tamaño o de fuerzas con el tiempo.",
  cronómetro: "Reloj que mide el tiempo con mucha precisión.",
  cuaderno: "Libro con hojas en blanco o rayadas para escribir o dibujar.",
  cuidado: "Atención para no romper algo o no hacer daño.",
  cuidando: "Protegiendo y atendiendo para que esté bien.",
  cuidarlas: "Protegerlas y atenderlas para que crezcan bien.",
  cuidaron: "Protegieron y atendieron para que estuviera bien.",
  cuidarse: "Protegerse y hacer cosas para mantenerse sano y seguro.",
  cumpleaños: "Día en que se celebra el año que cumplió una persona.",
  curiosidad: "Ganas de saber y descubrir cosas nuevas.",
  decidieron: "Eligieron juntos qué hacer.",
  decorada: "Adornada con dibujos, colores u otros detalles bonitos.",
  decoraron: "Adornaron con dibujos, colores u otros detalles.",
  delantera: "Parte de adelante de algo, como la punta de un barco o auto.",
  deliciosa: "Con un sabor muy rico y agradable.",
  demasiada: "Más de lo necesario o de lo correcto.",
  desaparece: "Deja de verse o de estar en un lugar.",
  desaparecía: "Dejaba de verse o de estar en un lugar.",
  desaparecían: "Dejaban de verse o de estar en un lugar.",
  desayunar: "Comer por la mañana la primera comida del día.",
  desayuno: "Primera comida del día, por la mañana.",
  desconocidos: "Personas que no conocemos todavía.",
  descubrieron: "Encontraron algo que no sabían antes.",
  deslizaron: "Se movieron suavemente sobre una superficie.",
  desordenada: "Que no guarda las cosas en su lugar.",
  despertaba: "Dejaba de dormir y abría los ojos.",
  despertador: "Reloj que suena a una hora para despertarnos.",
  despidieron: "Dijeron adiós al partir.",
  detective: "Persona que investiga y busca pistas para resolver un misterio.",
  detenerse: "Dejar de moverse o de hacer algo.",
  detuvieron: "Hicieron que algo o alguien dejara de moverse.",
  dibujadas: "Hechas con lápiz, marcador o pintura sobre papel.",
  dibujaron: "Hicieron dibujos con lápiz, marcador o pintura.",
  difíciles: "Que cuestan trabajo o no son fáciles de hacer.",
  dinosaurio: "Animal enorme que vivió hace millones de años.",
  dinosaurios: "Animales enormes que vivieron hace millones de años.",
  disfrutaron: "Pasaron un momento agradable y con gusto.",
  divertido: "Que causa risa, alegría o entretenimiento.",
  edificio: "Construcción grande con varios pisos donde viven personas o hay oficinas.",
  edificios: "Construcciones grandes con varios pisos.",
  embarcación: "Barco o bote que navega por el agua.",
  emigrante: "Persona que se mudó a otro país para vivir.",
  empezado: "Que ya dio el primer paso o comenzó.",
  empezaron: "Dieron el primer paso o iniciaron algo.",
  encargado: "Responsable de cuidar o hacer algo.",
  encendido: "Que está funcionando o con luz prendida.",
  encontraba: "Hallaba o veía algo al buscar.",
  encontraron: "Hallaron algo que buscaban.",
  enemigo: "Persona o ser que está en contra y causa daño.",
  enojarse: "Ponerse molesto o enfadado.",
  ensalada: "Plato frío hecho con verduras, frutas u otros ingredientes mezclados.",
  enseñaron: "Mostraron a otros cómo hacer algo o les explicaron.",
  entenderlo: "Comprender qué significa o qué quiere decir.",
  entendieron: "Comprendieron el significado o la idea de algo.",
  entrenamiento: "Práctica repetida para mejorar en un deporte o habilidad.",
  entusiasmo: "Muchas ganas y alegría por hacer algo.",
  equilibrarse: "Mantener el cuerpo estable sin caerse.",
  equivocada: "Que no es la correcta; tiene un error.",
  equivocado: "Que no es el correcto; tiene un error.",
  equivocó: "Cometió un error o eligió lo incorrecto.",
  escapado: "Que salió de donde debía estar, sin permiso.",
  esconderse: "Ponerse en un lugar donde otros no te vean.",
  escondida: "Sin que los demás lo vean, a escondidas.",
  escondidas: "Sin que los demás lo noten, a escondidas.",
  escondido: "Guardado en un lugar donde cuesta encontrarlo.",
  escribiendo: "Formando letras y palabras con lápiz o bolígrafo.",
  escribieron: "Pusieron letras y palabras en papel.",
  escuchaba: "Prestaba atención a un sonido o a lo que decían.",
  escuchaban: "Prestaban atención a un sonido o a lo que decían.",
  escuchando: "Prestando atención a un sonido o voz.",
  escucharon: "Prestaron atención a un sonido o voz.",
  esperaba: "Aguardaba que pasara algo o que alguien llegara.",
  esperaban: "Aguardaban que pasara algo o que alguien llegara.",
  esperado: "Aguardado durante un tiempo con ilusión.",
  esperanza: "Confianza de que algo bueno puede pasar.",
  esperaron: "Aguardaron que pasara algo o que alguien llegara.",
  estacionamiento: "Lugar donde se dejan autos y otros vehículos.",
  estantería: "Mueble con estantes para guardar libros u objetos.",
  estatura: "Altura de una persona, qué tan alto es.",
  estudiantes: "Personas que van a la escuela a aprender.",
  estudiara: "Aprendiera leyendo o practicando en la escuela.",
  estuviera: "Se encontrara en cierto estado o lugar.",
  exámenes: "Pruebas en la escuela para ver cuánto se aprendió.",
  extraterrestre: "Ser imaginario o posible que vendría de otro planeta.",
  fascinaba: "Le causaba mucho interés y admiración.",
  fascinada: "Muy interesada y con admiración por algo.",
  favorita: "La que más le gusta a alguien.",
  favoritos: "Los que más le gustan a alguien.",
  felicitaron: "Le dijeron palabras de alegría por algo bueno que hizo.",
  felicitó: "Le dijo palabras de alegría por algo bueno que hizo.",
  fiesta: "Reunión alegre donde la gente celebra algo especial.",
  fotografió: "Tomó una foto con cámara.",
  gallinero: "Lugar donde viven las gallinas.",
  habitación: "Cuarto de una casa, como el dormitorio.",
  honestidad: "Cualidad de decir la verdad y actuar con rectitud.",
  hormiguero: "Lugar donde viven muchas hormigas juntas bajo tierra.",
  ignoraba: "No le prestaba atención o actuaba como si no existiera.",
  ignorarlo: "No prestarle atención o actuar como si no existiera.",
  ignoraron: "No le prestaron atención o actuaron como si no existiera.",
  iluminaba: "Daba luz a un lugar.",
  iluminó: "Hizo que algo se viera con más luz.",
  imaginaba: "Creaba imágenes o historias en su mente.",
  imaginación: "Capacidad de inventar ideas, imágenes o historias en la cabeza.",
  imaginó: "Creó una imagen o historia en su mente.",
  impaciencia: "Ansiedad por hacer algo ya, sin poder esperar tranquilo.",
  importaba: "Tenía valor o relevancia para alguien.",
  importante: "Que vale la pena y merece atención.",
  inauguraron: "Abrieron oficialmente un lugar nuevo con una celebración.",
  inauguró: "Abrió oficialmente un lugar nuevo con una celebración.",
  incómodo: "Que molesta o no deja estar a gusto.",
  indicaba: "Mostraba o señalaba dónde estaba algo.",
  ingrediente: "Cada cosa que se usa para preparar una comida.",
  instrucciones: "Pasos o reglas que explican cómo hacer algo.",
  instructivos: "Que enseñan cómo hacer algo paso a paso.",
  instrumento: "Objeto que sirve para hacer música o medir algo.",
  integrales: "Hechos con cereales completos, más sanos.",
  intentaban: "Probaban hacer algo aunque pudiera costar.",
  intentarlo: "Probar hacer algo aunque pueda costar.",
  intentaron: "Probaron hacer algo aunque pudiera costar.",
  intercambiaron: "Cada uno dio algo y recibió otra cosa a cambio.",
  intercambios: "Actos de dar una cosa y recibir otra a cambio.",
  inventaban: "Creaban algo nuevo con la imaginación.",
  investigación: "Búsqueda ordenada de información o respuestas.",
  investigaron: "Buscaron información y pistas para entender algo.",
  investigó: "Buscó información y pistas para entender algo.",
  invitación: "Pedido amable para que alguien vaya a un lugar o fiesta.",
  jardinero: "Persona que cuida plantas y jardines.",
  lamparita: "Luz pequeña, como una bombilla chica.",
  lentamente: "Sin apuro, a un ritmo tranquilo.",
  levantaba: "Ponía algo más arriba o se ponía de pie.",
  limonada: "Bebida fría y dulce hecha con limón y agua.",
  llevársela: "Tomarla y irse con ella a otro lugar.",
  llevárselas: "Tomarlas y irse con ellas a otro lugar.",
  luciérnaga: "Insecto que brilla en la oscuridad con su luz propia.",
  luciérnagas: "Insectos que brillan en la oscuridad con su luz propia.",
  madrugada: "Muy temprano, cuando aún es de noche o recién amanece.",
  maquinista: "Persona que conduce o maneja una máquina o un tren.",
  marineros: "Personas que trabajan en barcos.",
  mariposa: "Insecto con alas coloridas que vuela de flor en flor.",
  matemáticas: "Materia escolar sobre números, sumas y formas.",
  mecánico: "Persona que arregla autos y otras máquinas.",
  mecanismo: "Conjunto de piezas que hacen funcionar una máquina.",
  medianoche: "Hora muy tarde, en medio de la noche.",
  mensajero: "Persona o animal que lleva un mensaje o paquete a otro lugar.",
  migas: "Pedacitos muy pequeños que quedan cuando se parte o se come algo.",
  monitora: "Chica mayor que ayuda a cuidar o guiar a otros niños.",
  municipal: "Del municipio o de la ciudad, hecho por el gobierno local.",
  musicales: "Relacionados con la música o que tienen melodía.",
  naranja: "Color entre rojo y amarillo; también es una fruta redonda y jugosa.",
  naturaleza: "Plantas, animales, ríos, montañas y todo lo del medio ambiente.",
  necesidades: "Cosas que una persona o animal requiere para vivir bien.",
  necesita: "Requiere algo para poder hacer o tener algo.",
  necesitaba: "Requería algo para poder hacer o tener algo.",
  necesitan: "Requieren algo para poder hacer o tener algo.",
  necesitaran: "Requirieran algo para poder hacer o tener algo.",
  necesiten: "Requieran algo para poder hacer o tener algo.",
  observaba: "Miraba con atención algo que pasaba, sin moverse mucho.",
  observación: "Acto de mirar con atención para aprender o descubrir.",
  observarlo: "Mirarlo con atención para ver qué hace.",
  observaron: "Miraron con atención para ver qué pasaba.",
  océano: "Mar enorme que cubre gran parte del planeta.",
  oficina: "Lugar donde la gente trabaja sentada, con escritorio.",
  olvidada: "Que quedó sin que nadie la recordara.",
  olvidado: "Que se dejó de recordar o de tener presente.",
  ordenaba: "Ponía las cosas en su lugar con método.",
  ordenada: "Que guarda las cosas en su lugar y con método.",
  ordenados: "Puestos en su lugar, con todo en orden.",
  organizada: "Que planifica y ordena bien las tareas.",
  organizaron: "Planificaron y prepararon algo en conjunto.",
  organizó: "Planificó y preparó algo con método.",
  oscureció: "Se puso con poca luz, como de noche.",
  oscuridad: "Cuando no hay luz y casi no se ve nada.",
  oxidada: "Con óxido, el color rojizo que aparece en el metal viejo.",
  pajarito: "Pájaro pequeño.",
  pájaro: "Animal con plumas y alas que vuela; muchos cantan por la mañana.",
  panadería: "Tienda donde venden pan, facturas y otras cosas horneadas.",
  parpadeaban: "Abrían y cerraban los ojos rápido, muchas veces.",
  parpadeó: "Abrió y cerró los ojos rápido una vez.",
  participación: "Acto de tomar parte en una actividad con los demás.",
  pasillo: "Espacio largo y angosto que une habitaciones dentro de una casa o edificio.",
  peligrosa: "Que puede causar daño o accidente.",
  perezosa: "Que no quiere hacer esfuerzo y prefiere no moverse.",
  planificar: "Pensar con anticipación lo que se va a hacer.",
  plateadas: "De color plateado, como la plata o el aluminio.",
  plateado: "De color como la plata, gris brillante.",
  porcelana: "Material duro y blanco del que se hacen platos finos.",
  practicaba: "Repetía algo para mejorar o aprender.",
  preparaban: "Dejaban todo listo antes de hacer algo.",
  prepararon: "Dejaron todo listo antes de hacer algo.",
  profesora: "Mujer que enseña en la escuela.",
  programación: "Instrucciones que le dicen a una máquina qué debe hacer.",
  prometieron: "Dijeron que harían algo en el futuro.",
  rastro: "Señal o marca que deja alguien o algo al pasar, y que permite seguirlo.",
  realidad: "Lo que es de verdad, no inventado.",
  recargable: "Que se puede volver a cargar con energía, como una pila.",
  recicladas: "Transformadas para usarse otra vez y no tirarlas.",
  recogieron: "Juntaron cosas del suelo o de un lugar.",
  recordaba: "Tenía presente algo que pasó antes.",
  recordatorio: "Algo que ayuda a no olvidar una tarea o fecha.",
  recorrido: "Camino o trayecto que se hace de un lugar a otro.",
  recuperó: "Volvió a tener algo que antes había perdido.",
  reflejaba: "Devolvía la imagen o la luz como un espejo.",
  relámpago: "Destello de luz muy fuerte en el cielo durante una tormenta.",
  renacuajo: "Cría de la rana que vive en el agua y tiene cola.",
  repararon: "Arreglaron algo que estaba roto o dañado.",
  repetición: "Hacer algo otra vez, una vez más.",
  respiraba: "Tomaba y soltaba aire con los pulmones.",
  responsabilidad: "Deber de cuidar algo o cumplir con lo prometido.",
  responsable: "Que cuida de algo o de alguien y cumple su tarea.",
  revisaba: "Miraba con cuidado para comprobar que todo estuviera bien.",
  rompecabezas: "Juego con piezas que hay que encastrar para formar una figura.",
  saludaron: "Dijeron hola o levantaron la mano al ver a alguien.",
  satisfecho: "Contento porque consiguió lo que quería o comió bien.",
  separaron: "Pusieron cosas o personas en distintos lugares, lejos.",
  significaba: "Quería decir o representaba algo.",
  significó: "Quiso decir o representó algo importante.",
  silencioso: "Que hace poco ruido o guarda silencio.",
  sobrevivió: "Siguió vivo después de un peligro o accidente.",
  solamente: "Únicamente, solo eso y nada más.",
  soleado: "Con sol y buen tiempo, sin nubes.",
  solidario: "Que piensa en el bienestar de los demás.",
  tambaleó: "Se movió de un lado a otro como si fuera a caerse.",
  teléfono: "Aparato para hablar con alguien que está en otro lugar.",
  telescopio: "Instrumento para ver objetos muy lejanos, como la Luna o las estrellas.",
  telescopios: "Instrumentos para ver cosas muy lejanas en el cielo.",
  televisión: "Aparato que muestra programas e imágenes en una pantalla.",
  temperatura: "Medida de qué tan caliente o frío está algo.",
  terminaron: "Concluyeron o dejaron de hacer algo porque ya acabó.",
  terremoto: "Sacudida fuerte de la tierra que puede romper cosas.",
  territorio: "Zona de tierra que un animal o grupo considera suyo.",
  torta: "Postre dulce y esponjoso que se hornea, como un pastel o un bizcocho.",
  vacaciones: "Tiempo de descanso sin clases o sin trabajo.",
  valiente: "Que actúa con coraje aunque algo dé un poco de miedo.",
  vecina: "Mujer que vive cerca, en la misma calle o en el mismo edificio.",
  vecindario: "Conjunto de casas y calles donde viven los vecinos.",
  velocidad: "Rapidez con la que algo se mueve.",
  vendedora: "Mujer que vende productos en una tienda o mercado.",
  ventana: "Abertura en la pared con vidrio por donde entra luz y se mira afuera.",
  ventanilla: "Abertura pequeña en una pared o ventana para atender.",
  ventilaron: "Hicieron correr aire fresco por un lugar.",
  verdadero: "Real, que es de verdad y no inventado.",
  veterinario: "Médico de animales.",
  videojuegos: "Juegos electrónicos que se juegan en pantalla.",
  villancicos: "Canciones que se cantan en las fiestas de fin de año.",
  visitaba: "Iba a ver a alguien o a un lugar por un rato.",
  visitaban: "Iban a ver a alguien o a un lugar por un rato.",
  visitante: "Persona que va a ver un lugar o a otra persona.",
  visitantes: "Personas que van a ver un lugar o a otras personas.",
  zanahoria: "Verdura alargada de color naranja que crece bajo tierra.",
  zanahorias: "Verduras alargadas de color naranja que crecen bajo tierra.",
  zoológico: "Lugar donde se pueden ver animales de muchas partes del mundo.",
};

export function getDefinition(word: string): string | undefined {
  const key = word.toLowerCase().replace(/[^a-záéíóúüñ]/g, "");
  return WORD_DEFINITIONS[key];
}
