/** Definiciones cortas en español neutro latinoamericano para niños ~9 años. */
export const WORD_DEFINITIONS: Record<string, string> = {
  aburrida: "Que no resulta divertida ni interesante.",
  aburrido: "Que no resulta divertido ni interesante.",
  aclarara: "Se volviera más claro, sin nubes ni niebla.",
  aconsejó: "Le dio un consejo o una buena idea a alguien.",
  adelante: "Hacia el frente, hacia donde uno va.",
  adhesiva: "Que sirve para pegar cosas, como la cinta scotch.",
  agradeció: "Dijo gracias o mostró que valoraba un favor.",
  agujero: "Espacio vacío hecho a propósito o por desgaste.",
  albahaca: "Planta aromática que se usa para dar sabor a la comida.",
  almohada: "Cojín blando donde apoyamos la cabeza al dormir.",
  aluminio: "Papel plateado y delgado que se usa para envolver comida.",
  amabilidad: "Acto amable y considerado con otra persona.",
  amaneció: "Salió el sol y comenzó un nuevo día.",
  amanecía: "Iba saliendo el sol al empezar el día.",
  amarillo: "Color como el del sol o de un limón.",
  animales: "Seres vivos que se mueven, como perros, pájaros o ballenas.",
  antiguo: "Que es de hace mucho tiempo o que ya tiene muchos años.",
  anotaba: "Escribía algo en un cuaderno para acordarse después.",
  aparatos: "Máquinas o instrumentos que sirven para hacer algo.",
  apareció: "Se hizo visible o llegó de repente.",
  aplaudieron: "Golpearon las manos una contra otra para mostrar alegría.",
  aprendieron: "Descubrieron algo nuevo o adquirieron un saber.",
  arrugado: "Con muchas arrugas o dobleces, no liso.",
  atardecer: "Momento del día cuando el sol se está poniendo.",
  atravesar: "Pasar de un lado al otro de algo.",
  avanzara: "Se moviera hacia adelante paso a paso.",
  aventura: "Experiencia emocionante con algo de sorpresa o desafío.",
  aventuras: "Experiencias emocionantes y con sorpresas.",
  avergonzaba: "Le daba vergüenza o pena mostrarse.",
  balcón: "Parte de un edificio que sale hacia afuera, con baranda, en un piso alto.",
  biblioteca: "Lugar donde hay muchos libros para leer o pedir prestados.",
  binoculares: "Instrumento con dos lentes para ver cosas lejanas más grandes.",
  calcetines: "Prendas que cubren los pies dentro del zapato.",
  calendario: "Cuadro o agenda que muestra los días, semanas y meses del año.",
  caminando: "Yendo de un lugar a otro a pie.",
  caminaron: "Fueron de un lugar a otro a pie.",
  camiseta: "Prenda de algodón que se usa en el torso.",
  campamento: "Lugar al aire libre donde se duerme en carpas y se hacen actividades.",
  campanitas: "Sonidos suaves y claros, como los de una campana pequeña.",
  caracoles: "Animales lentos con concha en espiral.",
  cerezas: "Frutas pequeñas, redondas y rojas que crecen en pares en un árbol.",
  chocolate: "Dulce suave y sabroso que se hace con cacao; puede ser oscuro o con leche.",
  cocinara: "Preparara comida en la cocina.",
  compartieron: "Dieron o usaron algo entre varios, en conjunto.",
  concentrado: "Muy enfocado en una sola cosa, sin distraerse.",
  conocida: "Que alguien ya sabía o había visto antes.",
  construyeron: "Armaron o fabricaron algo juntando piezas.",
  contratiempo: "Problema pequeño que retrasa o complica un plan.",
  convertirse: "Transformarse y pasar a ser otra cosa.",
  cosechado: "Recogido de la tierra cuando ya está listo para comer.",
  cronómetro: "Reloj que mide el tiempo con mucha precisión.",
  cuaderno: "Libro con hojas en blanco o rayadas para escribir o dibujar.",
  cuidado: "Atención para no romper algo o no hacer daño.",
  cuidarlas: "Protegerlas y atenderlas para que crezcan bien.",
  cumpleaños: "Día en que se celebra el año que cumplió una persona.",
  curiosidad: "Ganas de saber y descubrir cosas nuevas.",
  decorada: "Adornada con dibujos, colores u otros detalles bonitos.",
  decoraron: "Adornaron con dibujos, colores u otros detalles.",
  deliciosa: "Con un sabor muy rico y agradable.",
  demasiada: "Más de lo necesario o de lo correcto.",
  desaparece: "Deja de verse o de estar en un lugar.",
  desaparecía: "Dejaba de verse o de estar en un lugar.",
  desaparecían: "Dejaban de verse o de estar en un lugar.",
  desayunar: "Comer por la mañana la primera comida del día.",
  desayuno: "Primera comida del día, por la mañana.",
  deslizaron: "Se movieron suavemente sobre una superficie.",
  desordenada: "Que no guarda las cosas en su lugar.",
  despertaba: "Dejaba de dormir y abría los ojos.",
  despertador: "Reloj que suena a una hora para despertarnos.",
  detective: "Persona que investiga y busca pistas para resolver un misterio.",
  dibujadas: "Hechas con lápiz, marcador o pintura sobre papel.",
  dibujaron: "Hicieron dibujos con lápiz, marcador o pintura.",
  dinosaurios: "Animales enormes que vivieron hace millones de años.",
  divertido: "Que causa risa, alegría o entretenimiento.",
  edificio: "Construcción grande con varios pisos donde viven personas o hay oficinas.",
  embarcación: "Barco o bote que navega por el agua.",
  empezaron: "Dieron el primer paso o iniciaron algo.",
  encargado: "Responsable de cuidar o hacer algo.",
  encontraba: "Hallaba o veía algo al buscar.",
  enojarse: "Ponerse molesto o enfadado.",
  ensalada: "Plato frío hecho con verduras, frutas u otros ingredientes mezclados.",
  entendieron: "Comprendieron el significado o la idea de algo.",
  entusiasmo: "Muchas ganas y alegría por hacer algo.",
  equivocada: "Que no es la correcta; tiene un error.",
  equivocado: "Que no es el correcto; tiene un error.",
  escapado: "Que salió de donde debía estar, sin permiso.",
  esconderse: "Ponerse en un lugar donde otros no te vean.",
  escondidas: "Sin que los demás lo noten, a escondidas.",
  escondido: "Guardado en un lugar donde cuesta encontrarlo.",
  escribiendo: "Formando letras y palabras con lápiz o bolígrafo.",
  escuchaba: "Prestaba atención a un sonido o a lo que decían.",
  escuchaban: "Prestaban atención a un sonido o a lo que decían.",
  esperado: "Aguardado durante un tiempo con ilusión.",
  estantería: "Mueble con estantes para guardar libros u objetos.",
  estuviera: "Se encontrara en cierto estado o lugar.",
  fascinaba: "Le causaba mucho interés y admiración.",
  fascinada: "Muy interesada y con admiración por algo.",
  favorita: "La que más le gusta a alguien.",
  favoritos: "Los que más le gustan a alguien.",
  fiesta: "Reunión alegre donde la gente celebra algo especial.",
  hormiguero: "Lugar donde viven muchas hormigas juntas bajo tierra.",
  iluminó: "Hizo que algo se viera con más luz.",
  ignoraba: "No le prestaba atención o actuaba como si no existiera.",
  imaginaba: "Creaba imágenes o historias en su mente.",
  imaginación: "Capacidad de inventar ideas, imágenes o historias en la cabeza.",
  importaba: "Tenía valor o relevancia para alguien.",
  importante: "Que vale la pena y merece atención.",
  indicaba: "Mostraba o señalaba dónde estaba algo.",
  ingrediente: "Cada cosa que se usa para preparar una comida.",
  instrucciones: "Pasos o reglas que explican cómo hacer algo.",
  intentarlo: "Probar hacer algo aunque pueda costar.",
  intentaron: "Probaron hacer algo aunque pudiera costar.",
  intercambiaron: "Cada uno dio algo y recibió otra cosa a cambio.",
  intercambios: "Actos de dar una cosa y recibir otra a cambio.",
  inventaban: "Creaban algo nuevo con la imaginación.",
  investigación: "Búsqueda ordenada de información o respuestas.",
  lentamente: "Sin apuro, a un ritmo tranquilo.",
  luciérnaga: "Insecto que brilla en la oscuridad con su luz propia.",
  luciérnagas: "Insectos que brillan en la oscuridad con su luz propia.",
  maquinista: "Persona que conduce o maneja una máquina o un tren.",
  marineros: "Personas que trabajan en barcos.",
  mariposa: "Insecto con alas coloridas que vuela de flor en flor.",
  medianoche: "Hora muy tarde, en medio de la noche.",
  migas: "Pedacitos muy pequeños que quedan cuando se parte o se come algo.",
  necesitaba: "Requería algo para poder hacer o tener algo.",
  naranja: "Color entre rojo y amarillo; también es una fruta redonda y jugosa.",
  observaba: "Miraba con atención algo que pasaba, sin moverse mucho.",
  océano: "Mar enorme que cubre gran parte del planeta.",
  olvidado: "Que se dejó de recordar o de tener presente.",
  ordenada: "Que guarda las cosas en su lugar y con método.",
  organizada: "Que planifica y ordena bien las tareas.",
  organizaron: "Planificaron y prepararon algo en conjunto.",
  organizó: "Planificó y preparó algo con método.",
  oxidada: "Con óxido, el color rojizo que aparece en el metal viejo.",
  pájaro: "Animal con plumas y alas que vuela; muchos cantan por la mañana.",
  panadería: "Tienda donde venden pan, facturas y otras cosas horneadas.",
  pasillo: "Espacio largo y angosto que une habitaciones dentro de una casa o edificio.",
  peligrosa: "Que puede causar daño o accidente.",
  perezosa: "Que no quiere hacer esfuerzo y prefiere no moverse.",
  planificar: "Pensar con anticipación lo que se va a hacer.",
  plateadas: "De color plateado, como la plata o el aluminio.",
  prepararon: "Dejaron todo listo antes de hacer algo.",
  profesora: "Mujer que enseña en la escuela.",
  programación: "Instrucciones que le dicen a una máquina qué debe hacer.",
  prometieron: "Dijeron que harían algo en el futuro.",
  recuperó: "Volvió a tener algo que antes había perdido.",
  recordaba: "Tenía presente algo que pasó antes.",
  recordatorio: "Algo que ayuda a no olvidar una tarea o fecha.",
  relámpago: "Destello de luz muy fuerte en el cielo durante una tormenta.",
  renacuajo: "Cría de la rana que vive en el agua y tiene cola.",
  repararon: "Arreglaron algo que estaba roto o dañado.",
  respiraba: "Tomaba y soltaba aire con los pulmones.",
  revisaba: "Miraba con cuidado para comprobar que todo estuviera bien.",
  rompecabezas: "Juego con piezas que hay que encastrar para formar una figura.",
  rastro: "Señal o marca que deja alguien o algo al pasar, y que permite seguirlo.",
  satisfecho: "Contento porque consiguió lo que quería o comió bien.",
  solamente: "Únicamente, solo eso y nada más.",
  soleado: "Con sol y buen tiempo, sin nubes.",
  solidario: "Que piensa en el bienestar de los demás.",
  tambaleó: "Se movió de un lado a otro como si fuera a caerse.",
  telescopio: "Instrumento para ver objetos muy lejanos, como la Luna o las estrellas.",
  teléfono: "Aparato para hablar con alguien que está en otro lugar.",
  torta: "Postre dulce y esponjoso que se hornea, como un pastel o un bizcocho.",
  vacaciones: "Tiempo de descanso sin clases o sin trabajo.",
  valiente: "Que actúa con coraje aunque algo dé un poco de miedo.",
  vecina: "Mujer que vive cerca, en la misma calle o en el mismo edificio.",
  ventana: "Abertura en la pared con vidrio por donde entra luz y se mira afuera.",
  verdadero: "Real, que es de verdad y no inventado.",
  villancicos: "Canciones que se cantan en las fiestas de fin de año.",
  visitaba: "Iba a ver a alguien o a un lugar por un rato.",
  visitaban: "Iban a ver a alguien o a un lugar por un rato.",
  zanahoria: "Verdura alargada de color naranja que crece bajo tierra.",
};

export function getDefinition(word: string): string | undefined {
  const key = word.toLowerCase().replace(/[^a-záéíóúüñ]/g, "");
  return WORD_DEFINITIONS[key];
}
